[theme]
base = "light"
primaryColor = "#0A7C75"
backgroundColor = "#F8FBFC"
secondaryBackgroundColor = "#EAF1F5"
textColor = "#071B33"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

